<?php 
    $title = 'BUSCAR ALUMNO';
    $this->headTitle($title);   
?>

<div class="col-xs-12 col-sm-6 col-md-10 sidenav_cont">      
    <div class="conteiner form_serch" style="<?= $height ?>">

        <h1 class="text-center"><?= $this->escapeHtml($title) ?></h1><br>
        <div class="row" style="width: 100%;">
            <form name="serch-form" id="serch-form" action="<?= $this->url("plantel", ['action'=>'buscaralumno']); ?>" method="post" class=" col-xs-4" style="margin-left: 5%">
                <input id="status" name="status" type="text" value="1" hidden>
                <span>Ingresa la matr&iacute;cula del alumno:</span><br>
                <div class="input-group">
                    <input name="serch" id="serch" type="text" class="form-control" placeholder="Buscar matr&iacute;cula..." minlength="9" maxlength="9" required style="text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" value="" autocomplete="off" autofocus>
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit" id="serch-btn"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>

        <?php if($band == 2){ ?>
        <div class="row" style="margin-top: 2%">
                    <?php if(count($resultado) > 3){ ?>
                        <h3 class="text-center" style="color: #00756d; font-style: italic"><b><?= $resultado["status"] ?></b></h3>
                        <table class="table table-bordered text-right raised marca_agua">
                            <tbody>
                            <tr>
                                <td>&nbsp;</td>
                                <td class="text-center">
                                    <img src="<?= $this->basePath('img/logo_cb2.png')?>" class="img-responsive" id="logo">
                                </td>
                                <td>
                                    <b><p class="text-center" style="font-size:18px;margin-top:25px;"><?= $resultado["modalidad"] ?></p></b>
                                    <b>&nbsp;<p class="text-center" style="font-size:18px;color: red;"><?= $resultado["turno"] ?></p></b>
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><h3 class="cred"><b><?= $resultado["nombre"] ?></b></h3>
                                    <h3 class="cred"><b><?= $resultado["apellidos"] ?></b></h3>
                                </td>
                                <td rowspan="3">
                                           <?php
                                        if($resultado["img"] == ""){
                                            $foto = $this->basePath('img/noimagen.jpg');
                                        }else{
                                            $imdata = base64_encode($resultado["img"]);
                                            $foto = "data:image/jpg;base64,".$imdata;
                                        }
                                    ?>
                                    <img src="<?= $foto ?>" id="foto_std" style=" align-content: left;border: 2px solid #00a89c;border-radius: 5px;padding: 5px; ">
                                </td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><h3 class="cred"><p style="font-size: 12px">MATRICULA</p><b><?= $resultado["matricula"] ?></b></h3></td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>
                                    <h3 class="cred"><p style="font-size: 12px">CURP</p><b><?= $resultado["curp"] ?></b></h3><br>
                                    <h4 class="cred"><p style="font-size: 12px">CORREO</p><b><?= $resultado["correo"] ?></b></h4>
                                </td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td rowspan="2"class="text-center">
                                    <img src="<?= $this->basePath('iconos/logoplantel_'.$resultado["plantel"].'.png')?>" class="img-responsive" id="logo">
                                </td>
                                <td></td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>

                            </tbody>
                        </table>
                        

                    <?php }else{ ?>
                        <div style="width: 100%; margin-top:7%;" class="text-center">
                            <h3 style="font-style: italic; color: #00645d; font-weight: bold" class="text-center"><?= $resultado ?></h3>
                        </div>
                    <?php } ?>
                </div>
        
        <?php } ?>

    </div>
</div>
