<?php
    $title = 'CARGAR SOLICITUDES';
    $this->headTitle($title);
?>

<div class="col-xs-12 col-sm-6 col-md-10 sidenav_cont">      
    <div class="conteiner form_serch" style="<?= $css ?>">
    <?php if ($msj != "solicitudes cargadas"){
        if($band == 1 || (($msj == "registros cargados" || $msj == "No se pudo realizar la carga") || ($resultado["archivo"] == "Archivo no valido"))){ ?>
            <h1 class="text-center"><?= $this->escapeHtml($title) ?></h1><br>
            <form name="carga-form" id="carga-form" action="<?= $this->url.'/reposicion/cargarsolicitud'?>" method="post" enctype="multipart/form-data" target="_blank" >
                <input id="file-5" type="file" name="solicitudes" class="inputfile inputfile-4" placeholder="Selecciona un archivo&hellip;" data-multiple-caption="{count} files selected" multiple require/>
                <label for="file-5"><figure><svg xmlns="http://www.w3.org/2000/svg" width="20" height="17" viewBox="0 0 20 17"><path d="M10 0l-5.2 4.9h3.3v5.1h3.8v-5.1h3.3l-5.2-4.9zm9.3 11.5l-3.2-2.1h-2l3.4 2.6h-3.5c-.1 0-.2.1-.2.1l-.8 2.3h-6l-.8-2.2c-.1-.1-.1-.2-.2-.2h-3.6l3.4-2.6h-2l-3.2 2.1c-.4.3-.7 1-.6 1.5l.6 3.1c.1.5.7.9 1.2.9h16.3c.6 0 1.1-.4 1.3-.9l.6-3.1c.1-.5-.2-1.2-.7-1.5z"/></svg></figure><span>Selecciona un archivo&hellip;</span></label>
                <button class="btn btn-default btn-md" type="submit" id="cargar-btn" name="cargar-btn" style="width: 50%"> SUBIR DATOS </button>
            </form>
    <?php }
        }else{ ?>
        <h1 class="text-center">REPOSICI&Oacute;N DE CREDENCIALES</h1><br>
        <div class="row" style="width: 100%;">
            <form name="ordenar-form" id="ordenar-form" action="<?= $this->url("reposicion", ['action'=>'reposiciones']); ?>" method="post" class="form-inline" style="width: 100%; margin:0 0 3% 16%">
                <div class="form-group" style="width: 35%; height: 10%">
                    <label class="control-label" for="date">Fecha de Solicitud*:&nbsp;</label>
                    <div class="input-group date" id="date" name="date" style=""> <!-- Date input -->
                        <input class="form-control" id="date" name="date" style="font-size: 17px" type="text" value="<?= $resultado["fecha"] ?>" required placeholder="Fecha solicitud"/>
                        <span class="input-group-addon" id="calendar" onclick=""><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>

                <button class="btn btn-default btn-md" type="submit" id="serch-btn" style="width: 10%"> Buscar </button>
            </form>
        </div>

        <h3 style="text-align: center; margin: 2% 0 2% 0; font-style: italic; color: #00645d; font-weight: bold">Se cargaron <?= $resultado["registros"] ?> registros a la base de datos con fecha de <?= $resultado["fecha"] ?>.</h3>
    <?php }?>

	    <?php if($band == 2){
	        if ($msj == "registros cargados"){?>
                <div style="width: 100%; margin-top:5%;" class="text-center">
                    <h3 style="font-style: italic;font-weight: bold; color: #00645d;" class="text-center">Los registros con fecha del <?= $resultado["fecha"] ?> ya fueron cargados a la Base de Datos.</h3>
                </div>
            <?php }elseif($msj == "No se pudo realizar la carga"){ ?>
                 <div style="width: 100%; margin-top:5%;" class="text-center">
                    <h3 style="font-style: italic;font-weight: bold; color: #00645d;" class="text-center">No se pudo realizar la carga de las solicitudes, favor de revisar su correo para verificar el error</h3>
                </div>    
            <?php }elseif($resultado["archivo"] == "Archivo no valido"){ ?>
                <div style="width: 100%; margin-top:5%;" class="text-center">
                    <h3 style="font-style: italic;font-weight: bold; color: #00645d;" class="text-center">El archivo seleccionado no es v&aacute;lido. Seleccione un archivo que cumpla con las caracter&iacute;sticas de Siiaa</h3>
                </div>
            <?php }elseif($msj == "solicitudes cargadas"){ ?>
                        <div class="row">
                            <?php foreach ($plantel as $plt){ $i=0; $j=1; ?>
                                <div class="row">
                                    <div class="row" class="titulo_boton" onclick="muestra_oculta('contenido<?= $plt ?>')" id="mostrar">
                                        <h4 class="text-center" style="font-weight: bold">&nbsp;&nbsp;PLANTEL <?= $plt ?> </h4>
                                    </div>
                                    <div class="row" id="contenido<?= $plt ?>" style="display: none">
                                        <table class="table table-striped" style="width: 85%" id="tabla<?= $plt ?>">
                                            <!-- los datos van ordenados por fecha, plantel,nombre asc-->
                                            <thead>
                                            <tr>
                                                <td class="text-center" style="font-size: 16px">ID</td>
                                                <?php if(array_search('ID_IMPRESION', $_SESSION['opc'])){ ?>
                                                    <td class="text-center" style="font-size: 16px" data-campo='id'>ID IMPRESI&Oacute;N</td>
                                                <?php }?>
                                                <td class="text-center" style="font-size: 16px" data-campo='matricula'>MATRICULA</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='nombre'>NOMBRE</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='correo'>CORREO</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='pltl'>PLANTEL</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='fech_sol'>FECHA DE SOLICITUD</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='fech_imp'>FECHA DE IMPRESI&Oacute;N</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='fech_rev'>FECHA DE REVISI&Oacute;N</td>
                                                <td class="text-center" style="font-size: 16px" data-campo='fech_entr'>FECHA DE ENTREGA</td>
                                                <td class="text-center" style="font-size: 16px" >ESTATUS</td>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <?php if(array_search('CONFIRMAR_IMPRESION', $_SESSION['opc'])){ ?>
                                            <form id="impresion" name="impresion" action="<?= $this->url("reposicion", ['action'=>'reposicionesconf']); ?>" method="post">
                                                <input type="text" id="fecha" name="fecha" value="<?= $resultado["fecha"] ?>" hidden>
                                                <input type="text" id="plantel" name="plantel" value="<?= $plt ?>" hidden>
                                                <?php } ?>
                                                <?php
                                                foreach ($lista as $alum){
                                                    if ($alum[5] == $plt){ ?>
                                                        <?php if($alum[12] == 1){
                                                            $style='color: red;font-weight: bold';
                                                        }elseif ($alum[12] == 2){
                                                            $style='color: blue;font-weight: bold';
                                                        }elseif ($alum[12] == 3){
                                                            $style='color: green;font-weight: bold';
                                                        }elseif ($alum[12] == 4){
                                                            $style='color: #00958a;font-weight: bold';
                                                        }elseif ($alum[12] == 5){
                                                            $style='color: red;font-weight: bold';
                                                        } ?>
                                                        <tr id="<?= $alum[1] ?>">
                                                            <td class="text-center"><?= $j ?></td>
                                                            <?php $j++; ?>
                                                            <?php if(array_search('ID_IMPRESION', $_SESSION['opc'])){ ?>
                                                                <td class="text-center" data-campo='id_imp' style="<?= $style ?>"><?= $alum[0] ?></td>
                                                            <?php }?>
                                                            <td data-campo='matricula' style="<?= $style ?>"><p id="mat<?= $alum[1] ?>"><?= $alum[1] ?></p></td>
                                                            <td data-campo='nombre'><?= $alum[2]." ".$alum[3]." ".$alum[4] ?></td>
                                                            <td data-campo='correo'><?= $alum[9] ?></td>
                                                            <td class="text-center" data-campo='pltl'><?= $alum[5] ?></td>
                                                            <td class="text-center" data-campo='fech_sol'><?= $alum[7] ?></td>
                                                            <?php if(array_search('CONFIRMAR_IMPRESION', $_SESSION['opc']) AND $alum[12] == 1){ $i++; ?>
                                                                <td class="text-center" data-campo='fech_imp' id="imp">
                                                                    <div class="checkbox">
                                                                        <p id="imp<?= $alum[1] ?>"><input type="checkbox" id="mat<?= $i ?>" name="mat<?= $i ?>" value="<?= $alum[1] ?>" checked></p>
                                                                    </div>
                                                                </td>
                                                            <?php }else{ ?>
                                                                <td id="imp" class="text-center" data-campo='fech_imp'><p id="imp<?= $alum[1] ?>"><?= $alum[6] ?></p></td>
                                                            <?php } ?>
                                                            <td class="text-center" data-campo='fech_rev'><p id="rev<?= $alum[1] ?>"><?= $alum[8] ?></p></td>
                                                            <?php if(array_search('CONFIRMAR_ENTREGA', $_SESSION['opc']) AND $alum[10] == ""){ $i++;?>
                                                                <td id="ent<?= $alum[1] ?>" class="text-center" data-campo='fech_entr'>
                                                                    <div class="checkbox">
                                                                        <p id="ent<?= $alum[1] ?>"><input type="checkbox" name="mat<?= $i ?>" value="<?= $alum[1] ?>" checked></p>
                                                                    </div>
                                                                </td>
                                                            <?php }else{ ?>
                                                                <td id="ent<?= $alum[1] ?>" class="text-center" data-campo='fech_entr'><p id="ent<?= $alum[1] ?>"><?= $alum[10] ?></p></td>
                                                            <?php } ?>
                                                            <td data-campo='status' style="font-size: 16px;<?= $style ?>"><p id="stts<?= $alum[1] ?>"><?= $alum[11] ?></p></td>
                                                        </tr>
                                                    <?php } ?>
                                                <?php } //FIN FOREACH matriculas?>
                                            </tbody>
                                        </table>

                                        <?php if(array_search('CONFIRMAR_IMPRESION', $_SESSION['opc']) and $i != 0  and $band == 2){ ?>
                                                <input id="contador" name="contador" type="text" value="<?= $i ?>" hidden>
                                                <button id="btnconf<?= $plt ?>" name="btnconf<?= $plt ?>" type="submit" class="btn btn-default btn-md" style="margin-left: 80%;margin-bottom: 2%"> <span class="glyphicon glyphicon-ok"></span>&nbsp;Confirmar Impresi&oacute;n</button>
                                            </form>
                                        <?php }?>
                                        <?php if(array_search('CONFIRMAR_ENTREGA', $_SESSION['opc']) and $i != 0  and $band == 2){ ?>
                                            <button name="btnconf" type="submit" class="btn btn-default btn-md" style="margin-left: 80%;margin-bottom: 2%"> <span class="glyphicon glyphicon-ok"></span>&nbsp;Confirmar Entrega</button>
                                            </form>
                                        <?php }?>
                                    </div>
                                </div>
                                <?php }//FIN FOREACH plantel?>

                            <?php if(($_SESSION['perfil'] == 'SUPERUSUARIO' || $_SESSION['perfil'] == 'CARGA_SOLICITUDES') AND (count($resultado["errorCarg"]) > 0)){ ?>
                                <div class="row">
                                    <div class="row" class="titulo_boton" onclick="muestra_oculta('erroralum')" id="mostrar" style="color: red">
                                        <h4 class="text-center" style="font-weight: bold">&nbsp;&nbsp;ERROR EN CARGA </h4>
                                    </div>
                                    <div class="row" id="erroralum" style="display: none">
                                        <table class="table table-striped" style="width: 85%">
                                            <!-- los datos van ordenados por fecha, plantel,nombre asc-->
                                            <thead>
                                                <tr>
                                                    <td class="text-center" style="font-size: 16px" data-campo='matricula'>MATRICULA</td>
                                                    <td class="text-center" style="font-size: 16px" data-campo='nombre'>NOMBRE</td>
                                                    <td class="text-center" style="font-size: 16px" data-campo='correo'>CORREO</td>
                                                    <td class="text-center" style="font-size: 16px" data-campo='pltl'>PLANTEL</td>
                                                    <td class="text-center" style="font-size: 16px" data-campo='fech_sol'>FECHA DE SOLICITUD</td>
                                                    <td class="text-center" style="font-size: 16px" >ESTATUS</td>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            <?php  foreach ($resultado["errorCarg"] as $aux){?>
                                                <tr>
                                                    <td class="text-center" data-campo='matricula'><?= $aux[0] ?></td>
                                                    <td class="text-center" data-campo='nombre'><?= $aux[1]." ".$aux[2]." ".$aux[3] ?></td>
                                                    <td class="text-center" data-campo='correo'><?= $aux[6] ?></td>
                                                    <td class="text-center" data-campo='pltl'><?= $aux[4] ?></td>
                                                    <td class="text-center" data-campo='fech_sol'><?= $aux[5] ?></td>
                                                    <td class="text-center" style="font-size: 16px; color:red" >ALUMNO NO ENCONTRADO EN LA BD</td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            <?php } ?>


                <!-- M O D A L  -->
                 <div class="modal" id="modalForm">
                    <div class="modal-dialog" role="document">
                        <!-- MODAL CONTENT -->
                        <div class="modal-content">
                            <div class="row">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="row">
                                <h3 class="modal-title" id="modalFormL">Rechazar la solicitud del alumno con matr&iacute;cula <h3 id="matricula-h5" style="font-weight: bold; margin: 0"></h3></h3>
                            </div>
                            <div class="row" style="margin-top: 3%">
                                <form action="<?= $this->url("reposicion", ['action'=>'rechazarsol']); ?>" method="post" name="rechazo" id="rechazo">
                                    <div class="form-group" hidden>
                                        <input type="text" class="form-control" id="materror" name="materror" hidden>
                                        <input type="text" class="form-control" id="fecherror" name="fecherror" value="<?= $resultado["fecha"] ?>" hidden>
                                    </div>
                                    <div class="form-group" style="width: auto;">
                                        <label class="control-label" for="date">Escriba el motivo por el cu&aacute;l no se va a generar dicha solicitud:</label>
                                        <textarea class="form-control" id="motrech" name="motrech" style="text-transform:uppercase;" onkeyup="javascript:this.value=this.value.toUpperCase();" rows="2" placeholder="" rows="5" required autofocus></textarea>
                                    </div>
                                    <button id="btn-envrepor" name="btn-envrepor" class="btn btn-default">Enviar reporte</button>
                                </form>
                            </div>
                        </div>
                    </div>
                        </div>  
            <?php } ?>
      <?php }?>
    </div>
</div>


<script type="text/javascript">
    function muestra_oculta(id){
        if (document.getElementById){ //se obtiene el id
            var el = document.getElementById(id); //se define la variable "el" igual a nuestro div
            el.style.display = (el.style.display == 'none') ? 'block' : 'none'; //damos un atributo display:none que oculta el div
        }
    }
    
    $('input[type="checkbox"]').on('change', function (e) {
        if(this.checked == false){
            var mat = $(e.currentTarget).val();
            var modal = document.getElementById('modalForm');
            var span = document.getElementsByClassName("close")[0];

            console.log('Checkbox ' + mat + ' checked');

            document.getElementById("matricula-h5").innerHTML = mat;
            //document.getElementById("mat-error").innerHTML = mat;
            $('#materror').attr("value", mat);
            modal.style.display = "block";

            span.onclick = function () {
                modal.style.display = "none";
            }
            window.onclick = function (ev) {
                if(ev.target == modal){
                    modal.style.display = "none";
                }
            }
        }
    });

    $('#btn-envrepor').click(function (e) {
        e.preventDefault();
        var mat = $("#materror").val();
        var fecha = $("#fecherror").val();
        var motivo = $("#motrech").val();
        var modal = document.getElementById('modalForm');


        var matricula = "mat"+ mat;
        var p_imp = "#imp" + mat;
        var p_entr = "ent" + mat;
        var stts = "#stts" + mat;
        var rev = "rev" + mat;
        console.log("matricula: "+matricula, + " impresion: "+p_imp+ " status: "+stts);
        $.ajax({
            type:"POST",
            url: "/reposicion/reposiciones",
            data: {matr:mat, fecha:fecha,motivo:motivo},
            success: function (data, textStatus, xhr) {

                document.getElementById(matricula).style.color = "red";
                $(p_imp).text('');
                //document.getElementById(p_imp).innerHTML = "";
                document.getElementById(p_entr).innerHTML = "";
                document.getElementById(rev).innerHTML = "";
                //document.getElementById(stts).innerHTML = "";
                //document.getElementById(stts).style.color = "red";
                $(stts).text('RECHAZADA');

                modal.style.display = "none";
            }
        });
    });

</script>

